// NOTE This file is auto-generated by Contentlayer

import {
  SourceProvideSchemaErrorJSON,
  SourceFetchDataErrorJSON,
} from "contentlayer/core";
import { Post, Authors, DocumentTypes, DataExports } from "./types";

export * from "./types";

export declare const allPosts: Post[];
export declare const allAuthors: Authors[];

export declare const allDocuments: DocumentTypes[];
